# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# exp_model.py
# Created on: 2019-02-11 13:12:08.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: exp_model <Output_Feature_Class> <Input_Features> <Distance__value_or_field_> <Layer> <Intersect1> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Output_Feature_Class = arcpy.GetParameterAsText(0)

Input_Features = arcpy.GetParameterAsText(1)

Distance__value_or_field_ = arcpy.GetParameterAsText(2)

Layer = arcpy.GetParameterAsText(3)

Intersect1 = arcpy.GetParameterAsText(4)
if Intersect1 == '#' or not Intersect1:
    Intersect1 = "\\\\ds.leeds.ac.uk\\student\\student13\\mm15ks\\ArcGIS\\Default.gdb\\Intersect1" # provide a default value if unspecified

# Local variables:

# Process: Buffer
arcpy.Buffer_analysis(Input_Features, Output_Feature_Class, Distance__value_or_field_, "FULL", "ROUND", "NONE", "", "PLANAR")

# Process: Intersect
arcpy.Intersect_analysis([Layer, Output_Feature_Class], Intersect1, "ALL", "", "INPUT")

